import { Link } from 'react-router-dom'
import './Recommendations.css'

function CheckIcon() {
  return (
    <svg className="rec-check" viewBox="0 0 20 20" aria-hidden="true">
      <circle cx="10" cy="10" r="9" fill="none" stroke="currentColor" strokeWidth="1.5" />
      <path d="m6 10.3 2.8 2.8L14.2 7.4" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  )
}

function ArrowIcon() {
  return (
    <svg className="rec-arrow" viewBox="0 0 20 20" aria-hidden="true">
      <path d="M4 10h11m-4.5-4.5L15 10l-4.5 4.5" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  )
}

function meaningText(verdict) {
  if (verdict === 'Safe') {
    return 'This link passed the main safety checks and does not show obvious warning signs. Continue only if you recognize where it came from.'
  }
  if (verdict === 'Suspicious') {
    return 'This link has a few signals that deserve caution. It may be legitimate, but the connection and source are not fully trustworthy.'
  }
  return 'This link matches patterns commonly used to trick people or collect sensitive information. Treat it as unsafe and avoid interacting with it.'
}

function Recommendations({ result, saved }) {
  const download = () => {
    const previousTitle = document.title
    document.title = `ShieldCheck report - ${result.host || 'link'}`
    const restore = () => {
      document.title = previousTitle
      window.removeEventListener('afterprint', restore)
    }
    window.addEventListener('afterprint', restore)
    window.print()
  }

  const when = new Date(result.checkedAt || result.date)
  const checkedOn = Number.isNaN(when.getTime()) ? '' : when.toLocaleString()

  return (
    <section className="recommendations">
      <div className="meaning-box">
        <div>
          <p className="eyebrow">Next steps</p>
          <h2>What this means for you</h2>
          <p>{meaningText(result.verdict)}</p>
        </div>
        <div className="do-box">
          <h3>What you should do</h3>
          <ul>
            {result.recommendations.map((recommendation) => (
              <li key={recommendation}><CheckIcon />{recommendation}</li>
            ))}
          </ul>
        </div>
      </div>

      <div className="result-actions">
        {saved && <Link className="button button-secondary" to="/history">Back to history</Link>}
        <Link className="button button-primary" to="/">Check another link <ArrowIcon /></Link>
        <button className="button button-secondary" type="button" onClick={download}>Download report</button>
      </div>

      <p className="print-only">
        Report for {result.url}{checkedOn ? ` \u00B7 checked ${checkedOn}` : ''} \u00B7 Generated by ShieldCheck
      </p>
    </section>
  )
}
export default Recommendations